name: format-code

on: [push]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Format code
      run: |
        changed_files=$(git diff --name-only HEAD^)
        if [ -z "$changed_files" ]; then
          echo "No files were changed in the last commit. Formatting all .cpp and .hpp files in the repository."
          find . -name '*.cpp' -or -name '*.hpp' | while read filename; do
            clang-format -i $filename
          done
        else
          echo "$changed_files" | while read filename; do
            if [[ $filename == *.cpp || $filename == *.hpp ]]; then
              clang-format -i $filename
            fi
          done
        fi

    - name: Check for changes
      run: git diff

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --quiet || git commit -am "Automatically format code"
        git push