name: clang-format-check

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Get list of modified files
      id: files
      uses: dorny/paths-filter@v2
      with:
        filters: |
          source:
            - './**.cpp'
            - './**.hpp'

    - name: Run clang-format
      if: steps.files.outputs.source == 'true'
      uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: ${{ steps.files.outputs.files }}
        extensions: 'hpp,cpp'
        clangFormatVersion: 14
