name: format-code

on: [push]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Format code
      run: |
        git diff --name-only HEAD^ | while read filename; do
          if [[ $filename == *.cpp || $filename == *.h ]]; then
            clang-format -i $filename
          fi
        done

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --quiet || git commit -am "Automatically format code"
        git push