name: Clang Format

on:
  push:
    paths:
      - '**.cpp'
      - '***.hpp'
      - '**.h'

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Format code
        run: |
          git diff --name-only --diff-filter=d origin/main | grep -E ".*\.(cpp|h)$" | xargs clang-format -i

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -u
          git commit -m "Apply clang-format" || exit 0
          git push