name: test-clang-format
on:
  push:
    branches:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format
    - name: Copy .clang-format
      run: cp .clang-format ./
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: './src/pxl ./include/pxl'
        extensions: 'hpp,cpp'