name: test-clang-format

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format
    - name: Run clang-format
      run: clang-format -i ${{ github.workspace }}/src/pxl ${{ github.workspace }}/include/pxl